<a href="https://colab.research.google.com/github/tedkoo0212/Tensorflow/blob/main/%EC%8B%A4%EC%8A%B54_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85_'%EB%B6%84%EB%A5%98'.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# pandas가 one-hot encoding을 친절하게 해준다
# IV : 4 , DV:1 ---one-hot encoding---> IV :4 , DV:3
# softmax, crossentropy: 분류 (crossentropy를 이용해서 나온값의 차이가 loss . 까지만 이해), mse: 회귀
# 원리를 아는 것보다 필요한 이유를 아는 것이 더 중요하다.
# 분류 예측
# ex1) 비가 오거나 안오거나 30%
# ex2) 시험에 합격할 확률 90퍼
# 즉, 확률값으로 접근 !
#
# sigmoid & softmax 비율로 예측하기 위해 확률로 사용 ,, 차이점이 뭘까?
#

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩

인코딩 = pd.get_dummies(아이리스)
print(인코딩.head())
print(인코딩.columns)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립 변수, 종속 변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 데이터로 모델을 학습시킵니다. (fitting)
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5500 - accuracy: 0.8800
Epoch 2/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5475 - accuracy: 0.9200
Epoch 3/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5449 - accuracy: 0.9200
Epoch 4/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5425 - accuracy: 0.9133
Epoch 5/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5412 - accuracy: 0.9000
Epoch 6/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5388 - accuracy: 0.9133
Epoch 7/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.5361 - accuracy: 0.9200
Epoch 8/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5337 - accuracy: 0.9200
Epoch 9/1000
5/5 [==============================] - 0s 2ms/step - loss: 0.5317 - accuracy: 0.9067
Epoch 10/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.5290 - accuracy: 0.9133
Epoch 11/1000
5/5 [

In [ ]:
# loss 가 0에 크게 가까워졌고
# accuracy 또한 97퍼센트를 기록하며 100퍼센트에 매우 가까워졌다.

In [ ]:
# 모델을 이용합니다. (추정해봅니다.)

model.predict(독립[0:5])

array([[9.9953365e-01, 4.6638507e-04, 1.0689836e-08],
       [9.9757499e-01, 2.4249186e-03, 1.4154679e-07],
       [9.9908435e-01, 9.1563212e-04, 4.3583384e-08],
       [9.9754530e-01, 2.4544338e-03, 2.0543283e-07],
       [9.9966264e-01, 3.3735362e-04, 7.5414599e-09]], dtype=float32)

In [ ]:
# 난 왜 이렇게 다르지
# 나는 epochs 를 1000 이상으로 학습 시켜서, 
# 주어진 종속변수 데이터 값 ( 독립[0], 독립[1], ... 독립[5] ) 의 정확도(accuracy)가 매우 높은거구나?

In [ ]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
model.predict(독립[-5:])

array([[5.1001089e-06, 3.0831788e-02, 9.6916312e-01],
       [7.7900249e-06, 3.6963381e-02, 9.6302885e-01],
       [5.8308447e-06, 2.6668293e-02, 9.7332585e-01],
       [6.3945868e-06, 1.4707845e-02, 9.8528582e-01],
       [1.0780115e-05, 2.0365041e-02, 9.7962415e-01]], dtype=float32)

In [ ]:
# 학습한 가중치

model.get_weights()

[array([[-0.65269387,  0.7865919 ,  0.13393044],
        [ 0.7435671 , -0.00595671,  0.429667  ],
        [-0.8494812 , -0.5839968 ,  0.69642127],
        [ 0.25893092,  0.22931254,  0.16656184]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]