<a href="https://colab.research.google.com/github/tedkoo0212/Tensorflow/blob/main/%EC%8B%A4%EC%8A%B55_hiddenlayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# input layer ~ hidden layer ~ output layer
# Boston Estate Market Example
# (503,13) ~ (503,5) ~ (503,1)
# (13 -> 5) , (5 -> 1)
#
# modeling with one hidden layer
'''

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(3, activation='swish')(H)
H = tf.keras.layers.Dense(3, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)

model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')
'''


In [ ]:
# library 사용
import tensorflow as tf
import pandas as pd

In [ ]:
#1 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
보스턴.columns

#1-1 독립,종속 변수 설정
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
#2 모델의 구조를 만듭니다.
# 히든 레이어 3겹

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(3, activation='swish')(H)
H = tf.keras.layers.Dense(3, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)

model = tf.keras.models.Model(X,Y)
model.compile(loss='mse') #regression -> loss='mse'


In [ ]:
#3 모델을 학습시킵니다.
model.fit(독립,종속,epochs=1000)

Epoch 1/1000
16/16 [==============================] - 1s 2ms/step - loss: 813.0400
Epoch 2/1000
16/16 [==============================] - 0s 1ms/step - loss: 366.4486
Epoch 3/1000
16/16 [==============================] - 0s 1ms/step - loss: 215.9007
Epoch 4/1000
16/16 [==============================] - 0s 1ms/step - loss: 153.5988
Epoch 5/1000
16/16 [==============================] - 0s 2ms/step - loss: 128.6073
Epoch 6/1000
16/16 [==============================] - 0s 2ms/step - loss: 114.6605
Epoch 7/1000
16/16 [==============================] - 0s 2ms/step - loss: 106.0736
Epoch 8/1000
16/16 [==============================] - 0s 2ms/step - loss: 99.3295
Epoch 9/1000
16/16 [==============================] - 0s 2ms/step - loss: 94.2681
Epoch 10/1000
16/16 [==============================] - 0s 2ms/step - loss: 90.8340
Epoch 11/1000
16/16 [==============================] - 0s 2ms/step - loss: 88.2002
Epoch 12/1000
16/16 [==============================] - 0s 2ms/step - loss: 86.1409
Epoch 

In [ ]:
model.summary()
#한번씩 체크 해주는 것 좋다.

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 5)                 70        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 18        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 12        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 4         
Total params: 104
Trainable params: 104
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# parameter : 가중치의 개수
# Output Shape : 뭐지? 왜 None?
# 

In [ ]:
# 4 모델을 이용합니다 (추측을 해봅니다)
print(model.predict(독립[:5]))

[[31.438644]
 [23.267132]
 [31.866913]
 [35.207   ]
 [31.855469]]


In [ ]:
print(종속[:5])
# 이게 무슨 의미였지?


   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


## **아이리스 품종 분류**

In [1]:
# 1.과거의 데이터를 준비합니다.
# 2.원핫인코딩 (**)(하는 이유: Supervised Learning - Classification 이여서?)
# 3.독립 변수, 종속 변수
# 4.모델의 구조를 만듭니다.
# 5.데이터로 모델을 학습합니다.(FIT)
# 6.모델을 이용합니다.(추정해봅니다.)

In [3]:
import tensorflow as tf
import pandas as pd
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [9]:
아이리스 = pd.get_dummies(아이리스)
print(아이리스)
print(아이리스.columns)

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [12]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [13]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [14]:
model.fit(독립,종속,epochs=1000)

Epoch 1/1000
5/5 [==============================] - 1s 3ms/step - loss: 1.3208 - accuracy: 0.3333
Epoch 2/1000
5/5 [==============================] - 0s 2ms/step - loss: 1.0880 - accuracy: 0.3333
Epoch 3/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.0012 - accuracy: 0.3333
Epoch 4/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.9621 - accuracy: 0.3333
Epoch 5/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.9422 - accuracy: 0.3333
Epoch 6/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.9284 - accuracy: 0.3333
Epoch 7/1000
5/5 [==============================] - 0s 4ms/step - loss: 0.9125 - accuracy: 0.3400
Epoch 8/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.8985 - accuracy: 0.3333
Epoch 9/1000
5/5 [==============================] - 0s 3ms/step - loss: 0.8839 - accuracy: 0.3600
Epoch 10/1000
5/5 [==============================] - 0s 5ms/step - loss: 0.8667 - accuracy: 0.3667
Epoch 11/1000
5/5 [

In [15]:
print(model.predict(독립[:5]))
print(종속[0:5])

[[1.0000000e+00 2.0763782e-15 2.2576117e-09]
 [1.0000000e+00 6.4129496e-13 3.8888743e-08]
 [1.0000000e+00 4.3333030e-14 8.8702263e-09]
 [1.0000000e+00 1.2754136e-12 1.8188654e-08]
 [1.0000000e+00 9.6522994e-16 1.1851254e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
