<a href="https://colab.research.google.com/github/tedkoo0212/Tensorflow/blob/main/%EC%8B%A4%EC%8A%B52_%EB%A0%88%EB%AA%A8%EB%84%A4%EC%9D%B4%EB%93%9C_%ED%8C%90%EB%A7%A4_%EC%98%88%EC%B8%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터 준비
# 독립, 종속 나누어서 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [ ]:
# 종속 변수, 독립 변수
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
# 모델을 만듭니다 (modeling)
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [ ]:
# 모델을 학습시킵니다. (train)
model.fit(독립, 종속, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 4ms/step - loss: 791.8364
Epoch 2/2000
1/1 [==============================] - 0s 4ms/step - loss: 790.5208
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 789.2063
Epoch 4/2000
1/1 [==============================] - 0s 4ms/step - loss: 787.8929
Epoch 5/2000
1/1 [==============================] - 0s 4ms/step - loss: 786.5806
Epoch 6/2000
1/1 [==============================] - 0s 4ms/step - loss: 785.2693
Epoch 7/2000
1/1 [==============================] - 0s 3ms/step - loss: 783.9593
Epoch 8/2000
1/1 [==============================] - 0s 3ms/step - loss: 782.6502
Epoch 9/2000
1/1 [==============================] - 0s 3ms/step - loss: 781.3423
Epoch 10/2000
1/1 [==============================] - 0s 3ms/step - loss: 780.0356
Epoch 11/2000
1/1 [==============================] - 0s 4ms/step - loss: 778.7300
Epoch 12/2000
1/1 [==============================] - 0s 6ms/step - loss: 777.4255
Epoch 13/2000
1/1 [======

In [ ]:
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0173
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.0173
Epoch 3/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0173
Epoch 4/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0173
Epoch 5/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0173
Epoch 6/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0172
Epoch 7/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.0172
Epoch 8/1000
1/1 [==============================] - 0s 3ms/step - loss: 0.0172
Epoch 9/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0172
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.0172
Epoch 11/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.0172
Epoch 12/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.0172
Epoch 13/1000
1/1 [==============================

In [ ]:
# 모델을 이용합니다.
model.predict(독립)

array([[40.12738 ],
       [42.074375],
       [44.021366],
       [45.96836 ],
       [47.915356],
       [49.86235 ]], dtype=float32)

In [ ]:
종속

판매량
0   40
1   42
2   44
3   46
4   48
5   50

In [ ]:
model.predict([[15]])

array([[30.392408]], dtype=float32)

In [ ]:
model.predict([[5000]])

array([[9736.156]], dtype=float32)